import {
  Cake,
  SearchCheck,
  CheckCheck,
  Repeat2,
  Bot,
  FileText,
  Hash,
  Scale,
  CaseSensitive,
  Palette,
  Tag,
  Tags,
  BadgePercent,
  Landmark,
  Receipt,
  Globe2,
  Image,
  Crop,
  Eraser,
  Zap,
  Ruler,
  Instagram,
  RotateCw,
  Repeat,
  Braces,
  FileSpreadsheet,
  KeyRound,
  Unlock,
  BarChart3,
  Swords,
  MapPin,
  Lightbulb,
  Worm,
  Brain,
  Wheat,
  PenLine,
  FlaskConical,
  Link2,
  Wand2,
  ShieldOff,
  TrendingUp,
  SearchSlash,
  LineChart,
  Undo2,
  Timer,
  Twitter,
  Fingerprint,
  DollarSign,
  PenSquare,
  Mailbox,
  Building2,
  QrCode,
  UserRound,
  Dices,
  Wrench,
} from 'lucide-react';

// Maps a tool slug to a Lucide icon component, replacing the emoji
// previously stored in Tool.icon for on-screen rendering.
export const TOOL_ICON_MAP = {
  'age-calculator': Cake,
  'ai-content-detector': SearchCheck,
  'ai-grammar-checker': CheckCheck,
  'ai-paraphraser': Repeat2,
  'ai-text-humanizer': Bot,
  'ai-text-summarizer': FileText,
  'base64-encoder-decoder': Hash,
  'bmi-calculator': Scale,
  'case-converter': CaseSensitive,
  'color-picker': Palette,
  'css-minifier': Palette,
  'discount-calculator': BadgePercent,
  'emi-calculator': Building2,
  'gst-calculator': Receipt,
  'gstin-validator': Receipt,
  'hash-generator': Hash,
  'html-formatter': Globe2,
  'ifsc-code-finder': Landmark,
  'image-compressor': Image,
  'image-cropper': Crop,
  'image-metadata-viewer': SearchCheck,
  'image-optimizer': Zap,
  'image-resizer': Ruler,
  'instagram-hashtag-generator': Instagram,
  'jpg-to-png': RotateCw,
  'js-minifier': Zap,
  'json-formatter': Braces,
  'json-to-csv-converter': FileSpreadsheet,
  'jwt-decoder': Unlock,
  'keyword-density-checker': BarChart3,
  'keyword-difficulty-checker': Swords,
  'keyword-position-checker': MapPin,
  'keyword-suggestion-tool': Lightbulb,
  'long-tail-keyword-generator': Worm,
  'lorem-ipsum-generator': FileText,
  'lsi-keyword-generator': Brain,
  'mandi-price-checker': Wheat,
  'meta-description-generator': PenLine,
  'meta-tags-analyzer': FlaskConical,
  'meta-title-generator': Tag,
  'open-graph-tag-generator': Globe2,
  'password-generator': KeyRound,
  'percentage-calculator': BadgePercent,
  'pin-code-lookup': Mailbox,
  'png-to-jpg': RotateCw,
  'post-office-finder': Mailbox,
  'qr-code-generator': QrCode,
  'random-number-generator': Dices,
  'random-user-generator': UserRound,
  'regex-tester': SearchCheck,
  'related-keywords-finder': Link2,
  'remove-background': Wand2,
  'remove-duplicate-lines': Eraser,
  'remove-exif': ShieldOff,
  'search-volume-checker': LineChart,
  'serp-preview-tool': SearchCheck,
  'slug-generator': Link2,
  'text-repeater': Repeat,
  'text-reverser': Undo2,
  'timestamp-converter': Timer,
  'twitter-card-generator': Twitter,
  'uuid-generator': Fingerprint,
  'webp-converter': RotateCw,
  'word-counter': BarChart3,
  'youtube-description-generator': FileSpreadsheet,
  'youtube-earnings-calculator': DollarSign,
  'youtube-hashtag-generator': Hash,
  'youtube-tag-generator': Tags,
  'youtube-title-generator': PenSquare,
};

export function getToolIcon(slug) {
  return TOOL_ICON_MAP[slug] || Wrench;
}
